version: "3.0"

services:
  valmar:
    container_name: palantir-core
    #build:
    #  context: ../../
    #  dockerfile: tobeh.Palantir.Core/.docker/Dockerfile
    image: "ghcr.io/toobeeh/palantir-rebirth/palantir-core:latest"
    restart: unless-stopped
    #volumes:
    #  - path-to-appsettings.json:/app/appsettings.json
