version: "3.0"

services:
  palantir-core:
    container_name: palantir-commands
    build:
      context: ../../
      dockerfile: Palantir-Commands/.docker/Dockerfile 
    # image: "ghcr.io/toobeeh/palantir-rebirth/palantir-core:latest"
    restart: unless-stopped
    environment:
      - GRPC_VALMAR_URL=http://localhost:5175
      - GRPC_IMAGEGEN_URL=http://localhost:5176
      - DISCORD_TOKEN=token
