version: "3.0"

services:
  palantir-public:
    container_name: palantir-public
    # build:
    #  context: ../../
    #  dockerfile: tobeh.Palantir.Public/.docker/Dockerfile
    image: "ghcr.io/toobeeh/palantir-rebirth/palantir-core:latest"
    restart: unless-stopped
    #volumes:
    #  - path-to-appsettings.json:/app/appsettings.json
