version: "3.0"

services:
  palantir-lobbies:
    #build:
    #  context: ../../
    #  dockerfile: tobeh.Palantir.Lobbies/.docker/Dockerfile
    image: "ghcr.io/toobeeh/palantir-rebirth/palantir-core:latest"
    deploy:
      replicas: 5
    restart: unless-stopped
    #volumes:
    #  - path-to-appsettings.json:/app/appsettings.json
