// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: scenes.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Valmar {

  /// <summary>Holder for reflection information generated from scenes.proto</summary>
  public static partial class ScenesReflection {

    #region Descriptor
    /// <summary>File descriptor for scenes.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ScenesReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgxzY2VuZXMucHJvdG8SBnNjZW5lcxoeZ29vZ2xlL3Byb3RvYnVmL3dyYXBw",
            "ZXJzLnByb3RvGhtnb29nbGUvcHJvdG9idWYvZW1wdHkucHJvdG8iigIKClNj",
            "ZW5lUmVwbHkSDAoEbmFtZRgBIAEoCRILCgN1cmwYAiABKAkSCgoCaWQYAyAB",
            "KAUSEQoJZXhjbHVzaXZlGAQgASgIEjIKDHByaW1hcnlDb2xvchgFIAEoCzIc",
            "Lmdvb2dsZS5wcm90b2J1Zi5TdHJpbmdWYWx1ZRIyCgxndWVzc2VkQ29sb3IY",
            "BiABKAsyHC5nb29nbGUucHJvdG9idWYuU3RyaW5nVmFsdWUSLAoGYXJ0aXN0",
            "GAcgASgLMhwuZ29vZ2xlLnByb3RvYnVmLlN0cmluZ1ZhbHVlEiwKB2V2ZW50",
            "SWQYCCABKAsyGy5nb29nbGUucHJvdG9idWYuSW50MzJWYWx1ZSIdCg9HZXRT",
            "Y2VuZVJlcXVlc3QSCgoCaWQYASABKAUygwEKBlNjZW5lcxI8CgxHZXRBbGxT",
            "Y2VuZXMSFi5nb29nbGUucHJvdG9idWYuRW1wdHkaEi5zY2VuZXMuU2NlbmVS",
            "ZXBseTABEjsKDEdldFNjZW5lQnlJZBIXLnNjZW5lcy5HZXRTY2VuZVJlcXVl",
            "c3QaEi5zY2VuZXMuU2NlbmVSZXBseUIJqgIGVmFsbWFyYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.WrappersReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.EmptyReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Valmar.SceneReply), global::Valmar.SceneReply.Parser, new[]{ "Name", "Url", "Id", "Exclusive", "PrimaryColor", "GuessedColor", "Artist", "EventId" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Valmar.GetSceneRequest), global::Valmar.GetSceneRequest.Parser, new[]{ "Id" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// Response containing a scene's properties.
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class SceneReply : pb::IMessage<SceneReply>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SceneReply> _parser = new pb::MessageParser<SceneReply>(() => new SceneReply());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<SceneReply> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Valmar.ScenesReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SceneReply() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SceneReply(SceneReply other) : this() {
      name_ = other.name_;
      url_ = other.url_;
      id_ = other.id_;
      exclusive_ = other.exclusive_;
      PrimaryColor = other.PrimaryColor;
      GuessedColor = other.GuessedColor;
      Artist = other.Artist;
      EventId = other.EventId;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SceneReply Clone() {
      return new SceneReply(this);
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 1;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "url" field.</summary>
    public const int UrlFieldNumber = 2;
    private string url_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Url {
      get { return url_; }
      set {
        url_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 3;
    private int id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "exclusive" field.</summary>
    public const int ExclusiveFieldNumber = 4;
    private bool exclusive_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Exclusive {
      get { return exclusive_; }
      set {
        exclusive_ = value;
      }
    }

    /// <summary>Field number for the "primaryColor" field.</summary>
    public const int PrimaryColorFieldNumber = 5;
    private static readonly pb::FieldCodec<string> _single_primaryColor_codec = pb::FieldCodec.ForClassWrapper<string>(42);
    private string primaryColor_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string PrimaryColor {
      get { return primaryColor_; }
      set {
        primaryColor_ = value;
      }
    }


    /// <summary>Field number for the "guessedColor" field.</summary>
    public const int GuessedColorFieldNumber = 6;
    private static readonly pb::FieldCodec<string> _single_guessedColor_codec = pb::FieldCodec.ForClassWrapper<string>(50);
    private string guessedColor_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string GuessedColor {
      get { return guessedColor_; }
      set {
        guessedColor_ = value;
      }
    }


    /// <summary>Field number for the "artist" field.</summary>
    public const int ArtistFieldNumber = 7;
    private static readonly pb::FieldCodec<string> _single_artist_codec = pb::FieldCodec.ForClassWrapper<string>(58);
    private string artist_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Artist {
      get { return artist_; }
      set {
        artist_ = value;
      }
    }


    /// <summary>Field number for the "eventId" field.</summary>
    public const int EventIdFieldNumber = 8;
    private static readonly pb::FieldCodec<int?> _single_eventId_codec = pb::FieldCodec.ForStructWrapper<int>(66);
    private int? eventId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int? EventId {
      get { return eventId_; }
      set {
        eventId_ = value;
      }
    }


    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as SceneReply);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(SceneReply other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Name != other.Name) return false;
      if (Url != other.Url) return false;
      if (Id != other.Id) return false;
      if (Exclusive != other.Exclusive) return false;
      if (PrimaryColor != other.PrimaryColor) return false;
      if (GuessedColor != other.GuessedColor) return false;
      if (Artist != other.Artist) return false;
      if (EventId != other.EventId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (Url.Length != 0) hash ^= Url.GetHashCode();
      if (Id != 0) hash ^= Id.GetHashCode();
      if (Exclusive != false) hash ^= Exclusive.GetHashCode();
      if (primaryColor_ != null) hash ^= PrimaryColor.GetHashCode();
      if (guessedColor_ != null) hash ^= GuessedColor.GetHashCode();
      if (artist_ != null) hash ^= Artist.GetHashCode();
      if (eventId_ != null) hash ^= EventId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (Url.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Url);
      }
      if (Id != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Id);
      }
      if (Exclusive != false) {
        output.WriteRawTag(32);
        output.WriteBool(Exclusive);
      }
      if (primaryColor_ != null) {
        _single_primaryColor_codec.WriteTagAndValue(output, PrimaryColor);
      }
      if (guessedColor_ != null) {
        _single_guessedColor_codec.WriteTagAndValue(output, GuessedColor);
      }
      if (artist_ != null) {
        _single_artist_codec.WriteTagAndValue(output, Artist);
      }
      if (eventId_ != null) {
        _single_eventId_codec.WriteTagAndValue(output, EventId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (Url.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Url);
      }
      if (Id != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Id);
      }
      if (Exclusive != false) {
        output.WriteRawTag(32);
        output.WriteBool(Exclusive);
      }
      if (primaryColor_ != null) {
        _single_primaryColor_codec.WriteTagAndValue(ref output, PrimaryColor);
      }
      if (guessedColor_ != null) {
        _single_guessedColor_codec.WriteTagAndValue(ref output, GuessedColor);
      }
      if (artist_ != null) {
        _single_artist_codec.WriteTagAndValue(ref output, Artist);
      }
      if (eventId_ != null) {
        _single_eventId_codec.WriteTagAndValue(ref output, EventId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (Url.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Url);
      }
      if (Id != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Id);
      }
      if (Exclusive != false) {
        size += 1 + 1;
      }
      if (primaryColor_ != null) {
        size += _single_primaryColor_codec.CalculateSizeWithTag(PrimaryColor);
      }
      if (guessedColor_ != null) {
        size += _single_guessedColor_codec.CalculateSizeWithTag(GuessedColor);
      }
      if (artist_ != null) {
        size += _single_artist_codec.CalculateSizeWithTag(Artist);
      }
      if (eventId_ != null) {
        size += _single_eventId_codec.CalculateSizeWithTag(EventId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(SceneReply other) {
      if (other == null) {
        return;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.Url.Length != 0) {
        Url = other.Url;
      }
      if (other.Id != 0) {
        Id = other.Id;
      }
      if (other.Exclusive != false) {
        Exclusive = other.Exclusive;
      }
      if (other.primaryColor_ != null) {
        if (primaryColor_ == null || other.PrimaryColor != "") {
          PrimaryColor = other.PrimaryColor;
        }
      }
      if (other.guessedColor_ != null) {
        if (guessedColor_ == null || other.GuessedColor != "") {
          GuessedColor = other.GuessedColor;
        }
      }
      if (other.artist_ != null) {
        if (artist_ == null || other.Artist != "") {
          Artist = other.Artist;
        }
      }
      if (other.eventId_ != null) {
        if (eventId_ == null || other.EventId != 0) {
          EventId = other.EventId;
        }
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 18: {
            Url = input.ReadString();
            break;
          }
          case 24: {
            Id = input.ReadInt32();
            break;
          }
          case 32: {
            Exclusive = input.ReadBool();
            break;
          }
          case 42: {
            string value = _single_primaryColor_codec.Read(input);
            if (primaryColor_ == null || value != "") {
              PrimaryColor = value;
            }
            break;
          }
          case 50: {
            string value = _single_guessedColor_codec.Read(input);
            if (guessedColor_ == null || value != "") {
              GuessedColor = value;
            }
            break;
          }
          case 58: {
            string value = _single_artist_codec.Read(input);
            if (artist_ == null || value != "") {
              Artist = value;
            }
            break;
          }
          case 66: {
            int? value = _single_eventId_codec.Read(input);
            if (eventId_ == null || value != 0) {
              EventId = value;
            }
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 18: {
            Url = input.ReadString();
            break;
          }
          case 24: {
            Id = input.ReadInt32();
            break;
          }
          case 32: {
            Exclusive = input.ReadBool();
            break;
          }
          case 42: {
            string value = _single_primaryColor_codec.Read(ref input);
            if (primaryColor_ == null || value != "") {
              PrimaryColor = value;
            }
            break;
          }
          case 50: {
            string value = _single_guessedColor_codec.Read(ref input);
            if (guessedColor_ == null || value != "") {
              GuessedColor = value;
            }
            break;
          }
          case 58: {
            string value = _single_artist_codec.Read(ref input);
            if (artist_ == null || value != "") {
              Artist = value;
            }
            break;
          }
          case 66: {
            int? value = _single_eventId_codec.Read(ref input);
            if (eventId_ == null || value != 0) {
              EventId = value;
            }
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// Request containing a scene id
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class GetSceneRequest : pb::IMessage<GetSceneRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<GetSceneRequest> _parser = new pb::MessageParser<GetSceneRequest>(() => new GetSceneRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<GetSceneRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Valmar.ScenesReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetSceneRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetSceneRequest(GetSceneRequest other) : this() {
      id_ = other.id_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetSceneRequest Clone() {
      return new GetSceneRequest(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private int id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as GetSceneRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(GetSceneRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0) hash ^= Id.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Id);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(GetSceneRequest other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0) {
        Id = other.Id;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
