name: docker-build-palantir-lobbies

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/build-palantir-lobbies.yml'
      - 'tobeh.Palantir.Lobbies/**'
      - 'tobeh.Palantir.Commands/**'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./tobeh.Palantir.Lobbies/.docker/Dockerfile
          push: true
          tags: ghcr.io/toobeeh/palantir-rebirth/palantir-lobbies:latest
